apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebike-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebike-service
  template:
    metadata:
      labels:
        app: ebike-service
    spec:
      containers:
        - name: ebike-service
          image: marcofontana17/sap-ass-03:bike-service
          env:
            - name: CONFIG_SERVER_HOST_NAME
              value: "config-server"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 90
            timeoutSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: ebike-service
spec:
  selector:
    app: ebike-service
  ports:
    - port: 8080
      targetPort: 8080
