apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-bike-db
  namespace: ebike-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-bike-db
  template:
    metadata:
      labels:
        app: mysql-bike-db
    spec:
      containers:
        - name: mysql-bike-db
          image: marcofontana/sap-ass-03:bike-sql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "ebike"
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 40
            periodSeconds: 90
            timeoutSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-bike-db
  namespace: ebike-app
spec:
  selector:
    app: mysql-bike-db
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  type: ClusterIP
