apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-bike-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-bike-db
  template:
    metadata:
      labels:
        app: mongo-bike-db
    spec:
      containers:
        - name: mongo-bike-db
          image: marcofontana17/sap-ass-03:bike-mongo-db
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-bike-db
spec:
  selector:
    app: mongo-bike-db
  ports:
    - port: 27017
      targetPort: 27017
