apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-bike-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-bike-db
  template:
    metadata:
      labels:
        app: mysql-bike-db
    spec:
      containers:
        - name: mysql-bike-db
          image: marcofontana17/sap-ass-03:bike-sql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "ebike"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-bike-db
spec:
  selector:
    app: mysql-bike-db
  ports:
    - port: 3306
      targetPort: 3306
