apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user-db
  template:
    metadata:
      labels:
        app: mongo-user-db
    spec:
      containers:
        - name: mongo-user-db
          image: marcofontana/sap-ass-03:user-mongo-db
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user-db
  namespace: default
spec:
  selector:
    app: mongo-user-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
