package sap.ass02.domain.dto;

public enum BikeStateDTO {
    AVAILABLE, IN_USE, MOVING_TO_STATION, AT_STATION, MAINTENANCE, START_AUTONOMOUSLY_REACH_USER, MOVING_TO_USER, AT_USER, START_AUTONOMOUSLY_REACH_STATION
}